### ISSUE TITLE
loading duplicate scene protection not working

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#67]
loading scene twice is possible.
And when closing the duplicate scene the first loaded instance throws error -> `dict: no dictionary named SceneName, cannot access values` when pressings cues. 
This happens because the duplicate scene was closed and the associated data was freed.
Which makes sense of course.
also it seems that all osc and jamoma path stuff relative to global is afterwards completely fucked up. the only fix is to restart max and VTMGlobal..

**Comment by balintlaczko** [comment]
Yes, located the problem: it only happens when you try to open it for the second time using Max's menu (either *Open...* or *Open Recent Patcher*). Does not happen when trying to open for the 2nd time from Finder or when you open a scene set which has already opened scenes.

The solution will be partly to add a [onecopy] to the scene template patch. For how to fix this with the already existing scenes is yet to be invented... :)

**Comment by balintlaczko** [comment]
UPDATE: [onecopy] only prevents double opens if the patch is a member of Extras. Lolz.
