### ISSUE TITLE
Use the package Zero to do zeroconf/mDNS discovery of IP adresses

### ISSUE THREAD

**Issue by eirikblekesaune** [eirikblekesaune/VTMax#9]

**Comment by eirikblekesaune** [comment]
Probably good to choose _one_ method of doing it. Either dynamic discovery or telephone book.

**Comment by eirikblekesaune** [comment]
Might pose challenges when interfacing with a range of different systems that implement mDNSin various ways. E.g. statically defined/declared presets, cues, etc.

**Comment by balintlaczko** [comment]
Done (in a way). Instead of messing with the already established "phone book" system, my concept was rather to use zeroconf in a send & receive abstractions - because you might not need to have this functionality all the time. Now, if you want someone to mess for example with your cutoff, then you make an object: [VTMAnnounce "Balint's Cutoff"] and connect to your cutoff. On the same network people can now right click > Paste From > VTMax > UI > VTM_UI_Zerosend, which will show a dropdown menu and a "Refresh" button. The menu will contain all the announced "services" - such as Balint's Cutoff -, so you just select that, and send your numbers to it. In this way you can also save scenes with Announce and Zerosend objects, initialized automatically as you want, no ip addresses or ports are needed.
